"""add_telegram_fields_to_users

Revision ID: 08088987b6e6
Revises: dedbd89fad6a
Create Date: 2026-01-27 13:45:31.500846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08088987b6e6'
down_revision: Union[str, Sequence[str], None] = 'dedbd89fad6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('morning_briefing_time', sa.String(length=5), nullable=False, server_default='09:00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'morning_briefing_time')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
