"""add_project_management_tables

Revision ID: 3d8c242a2745
Revises: 0c0ac3d95f10
Create Date: 2026-01-27 14:15:09.550760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d8c242a2745'
down_revision: Union[str, Sequence[str], None] = '0c0ac3d95f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types first (if they don't exist)
    from sqlalchemy import text
    connection = op.get_bind()
    
    # Check and create each type
    result = connection.execute(text("SELECT 1 FROM pg_type WHERE typname = 'projectstatus'"))
    if not result.scalar():
        op.execute("CREATE TYPE projectstatus AS ENUM ('ACTIVE', 'BACKBURNER', 'DONE', 'ARCHIVED')")
    
    result = connection.execute(text("SELECT 1 FROM pg_type WHERE typname = 'taskstatus'"))
    if not result.scalar():
        op.execute("CREATE TYPE taskstatus AS ENUM ('TODO', 'IN_PROGRESS', 'DONE')")
    
    result = connection.execute(text("SELECT 1 FROM pg_type WHERE typname = 'taskpriority'"))
    if not result.scalar():
        op.execute("CREATE TYPE taskpriority AS ENUM ('HIGH', 'MEDIUM', 'LOW')")
    
    result = connection.execute(text("SELECT 1 FROM pg_type WHERE typname = 'taskenergylevel'"))
    if not result.scalar():
        op.execute("CREATE TYPE taskenergylevel AS ENUM ('HIGH', 'MEDIUM', 'LOW')")
    
    op.create_table('backburner_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resurfaced_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backburner_user', 'backburner_items', ['user_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_milestones_check_in_date', 'milestones', ['check_in_date'], unique=False)
    op.create_index('idx_milestones_project', 'milestones', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('projects', sa.Column('estimated_hours', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('actual_hours', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('moved_to_backburner_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('backburner_reason', sa.Text(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'BACKBURNER', 'DONE', 'ARCHIVED', name='projectstatus'),
               existing_nullable=False,
               postgresql_using='status::projectstatus')
    op.alter_column('projects', 'deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_projects_id', table_name='projects')
    op.create_index('idx_projects_deadline', 'projects', ['deadline'], unique=False)
    op.create_index('idx_projects_user_status', 'projects', ['user_id', 'status'], unique=False)
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'energy_level')
    op.drop_column('projects', 'name')
    op.drop_column('projects', 'extra_data')
    op.add_column('tasks', sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=False))
    op.add_column('tasks', sa.Column('energy_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='taskenergylevel'), nullable=False))
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               existing_nullable=False,
               postgresql_using='status::taskstatus')
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('idx_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_user_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_parent_task_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'difficulty')
    op.drop_column('tasks', 'estimated_time_minutes')
    op.drop_column('tasks', 'best_time_of_day')
    op.drop_column('tasks', 'requires_strategy')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'can_break_down')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'energy_needed')
    op.drop_column('tasks', 'actual_time_minutes')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'focus_needed')
    op.drop_column('tasks', 'best_energy_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('best_energy_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('focus_needed', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('actual_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('energy_needed', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('can_break_down', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('requires_strategy', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('best_time_of_day', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('estimated_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_parent_task_id_fkey', 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_user_id_fkey', 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_tasks_user_status', table_name='tasks')
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'estimated_minutes')
    op.drop_column('tasks', 'energy_level')
    op.drop_column('tasks', 'priority')
    op.add_column('projects', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('energy_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_projects_user_status', table_name='projects')
    op.drop_index('idx_projects_deadline', table_name='projects')
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.alter_column('projects', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('ACTIVE', 'BACKBURNER', 'DONE', 'ARCHIVED', name='projectstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('projects', 'backburner_reason')
    op.drop_column('projects', 'moved_to_backburner_at')
    op.drop_column('projects', 'actual_hours')
    op.drop_column('projects', 'estimated_hours')
    op.drop_column('projects', 'title')
    op.drop_index('idx_milestones_project', table_name='milestones')
    op.drop_index('idx_milestones_check_in_date', table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('idx_backburner_user', table_name='backburner_items')
    op.drop_table('backburner_items')
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS taskenergylevel")
    op.execute("DROP TYPE IF EXISTS taskpriority")
    op.execute("DROP TYPE IF EXISTS taskstatus")
    op.execute("DROP TYPE IF EXISTS projectstatus")
    # ### end Alembic commands ###
