"""Add reminders table with timezone support

Revision ID: 3b066e50a3e4
Revises: merge_to_pattern_system
Create Date: 2026-01-31 01:08:13.711629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b066e50a3e4'
down_revision: Union[str, Sequence[str], None] = 'merge_to_pattern_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SKIP: Don't drop pattern tables - they're still in use
    # op.drop_index('ix_pattern_observations_category', table_name='pattern_observations')
    # op.drop_index('ix_pattern_observations_date', table_name='pattern_observations')
    # op.drop_index('ix_pattern_observations_sub_pattern', table_name='pattern_observations')
    # op.drop_index('ix_pattern_observations_user', table_name='pattern_observations')
    # op.drop_table('pattern_observations')
    # op.drop_index('ix_pattern_categories_name', table_name='pattern_categories')
    # op.drop_index('ix_pattern_categories_user', table_name='pattern_categories')
    # op.drop_table('pattern_categories')
    # op.drop_index('ix_pattern_hypotheses_category', table_name='pattern_hypotheses')
    # op.drop_index('ix_pattern_hypotheses_confidence', table_name='pattern_hypotheses')
    # op.drop_index('ix_pattern_hypotheses_needs_exploration', table_name='pattern_hypotheses')
    # op.drop_index('ix_pattern_hypotheses_sub_pattern', table_name='pattern_hypotheses')
    # op.drop_index('ix_pattern_hypotheses_user', table_name='pattern_hypotheses')
    # op.drop_table('pattern_hypotheses')
    
    # Delete old reminders first (they have incompatible schema)
    op.execute("DELETE FROM reminders")
    
    op.add_column('reminders', sa.Column('task', sa.Text(), nullable=False))
    op.add_column('reminders', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('reminders', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('reminders', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reminders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_reminders_remind_at', table_name='reminders')
    op.drop_index('ix_reminders_sent', table_name='reminders')
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    op.create_index(op.f('ix_reminders_is_sent'), 'reminders', ['is_sent'], unique=False)
    op.create_index(op.f('ix_reminders_reminder_time'), 'reminders', ['reminder_time'], unique=False)
    op.drop_constraint('reminders_user_id_fkey', 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'remind_at')
    op.drop_column('reminders', 'message')
    op.drop_column('reminders', 'sent')
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='taskpriority'),
               nullable=True)
    op.alter_column('tasks', 'energy_level',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='taskenergylevel'),
               nullable=True)
    op.create_foreign_key(None, 'work_sessions', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_sessions', type_='foreignkey')
    op.alter_column('tasks', 'energy_level',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='taskenergylevel'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='taskpriority'),
               nullable=False)
    op.add_column('reminders', sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('reminders', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('reminders', sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key('reminders_user_id_fkey', 'reminders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reminders_reminder_time'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_is_sent'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.create_index('ix_reminders_sent', 'reminders', ['sent'], unique=False)
    op.create_index('ix_reminders_remind_at', 'reminders', ['remind_at'], unique=False)
    op.alter_column('reminders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('reminders', 'sent_at')
    op.drop_column('reminders', 'is_sent')
    op.drop_column('reminders', 'reminder_time')
    op.drop_column('reminders', 'context')
    op.drop_column('reminders', 'task')
    op.create_table('pattern_hypotheses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hypothesis', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supporting_observations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contradicting_observations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('needs_exploration', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pattern_categories.id'], name='pattern_hypotheses_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pattern_hypotheses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pattern_hypotheses_pkey')
    )
    op.create_index('ix_pattern_hypotheses_user', 'pattern_hypotheses', ['user_id'], unique=False)
    op.create_index('ix_pattern_hypotheses_sub_pattern', 'pattern_hypotheses', ['sub_pattern'], unique=False)
    op.create_index('ix_pattern_hypotheses_needs_exploration', 'pattern_hypotheses', ['needs_exploration'], unique=False)
    op.create_index('ix_pattern_hypotheses_confidence', 'pattern_hypotheses', ['confidence'], unique=False)
    op.create_index('ix_pattern_hypotheses_category', 'pattern_hypotheses', ['category_id'], unique=False)
    op.create_table('pattern_categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pattern_categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_system_category', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pattern_categories_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pattern_categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_pattern_categories_user', 'pattern_categories', ['user_id'], unique=False)
    op.create_index('ix_pattern_categories_name', 'pattern_categories', ['category_name'], unique=False)
    op.create_table('pattern_observations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sub_pattern', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('observed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['pattern_categories.id'], name='pattern_observations_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pattern_observations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pattern_observations_pkey')
    )
    op.create_index('ix_pattern_observations_user', 'pattern_observations', ['user_id'], unique=False)
    op.create_index('ix_pattern_observations_sub_pattern', 'pattern_observations', ['sub_pattern'], unique=False)
    op.create_index('ix_pattern_observations_date', 'pattern_observations', ['observed_at'], unique=False)
    op.create_index('ix_pattern_observations_category', 'pattern_observations', ['category_id'], unique=False)
    # ### end Alembic commands ###
