"""add all remaining tables

Revision ID: 7f6c46148b8a
Revises: ed844c5919cc
Create Date: 2026-01-27 09:27:01.486375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f6c46148b8a'
down_revision: Union[str, Sequence[str], None] = 'ed844c5919cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('calendar_source', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', 'calendar_source', name='uq_user_calendar_event')
    )
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('energy_rating', sa.Integer(), nullable=True),
    sa.Column('focus_rating', sa.Integer(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('stress_rating', sa.Integer(), nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('daily', 'weekly', 'monthly')", name='check_checkin_type'),
    sa.CheckConstraint('energy_rating >= 1 AND energy_rating <= 10', name='check_energy_rating'),
    sa.CheckConstraint('focus_rating >= 1 AND focus_rating <= 10', name='check_focus_rating'),
    sa.CheckConstraint('mood_rating >= 1 AND mood_rating <= 10', name='check_mood_rating'),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 10', name='check_overall_rating'),
    sa.CheckConstraint('stress_rating >= 1 AND stress_rating <= 10', name='check_stress_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("category IN ('personal', 'work')", name='check_goal_category'),
    sa.CheckConstraint("status IN ('active', 'completed', 'paused', 'abandoned')", name='check_goal_status'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='check_goal_progress'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('energy_level', sa.String(length=20), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("energy_level IN ('mixed', 'high_energy', 'low_energy')", name='check_project_energy'),
    sa.CheckConstraint("priority IN ('urgent', 'high', 'medium', 'low', 'someday')", name='check_project_priority'),
    sa.CheckConstraint("status IN ('active', 'on_hold', 'completed', 'someday')", name='check_project_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('wheel_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition_of_10', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_wheel_category')
    )
    op.create_index(op.f('ix_wheel_categories_id'), 'wheel_categories', ['id'], unique=False)
    op.create_table('conversation_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('pinecone_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pinecone_id')
    )
    op.create_index(op.f('ix_conversation_embeddings_id'), 'conversation_embeddings', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('energy_needed', sa.String(length=20), nullable=True),
    sa.Column('focus_needed', sa.String(length=20), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_time_minutes', sa.Integer(), nullable=True),
    sa.Column('best_time_of_day', sa.String(length=20), nullable=True),
    sa.Column('best_energy_state', sa.String(length=20), nullable=True),
    sa.Column('requires_strategy', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_break_down', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("best_energy_state IN ('high', 'medium', 'low', 'any')", name='check_task_energy_state'),
    sa.CheckConstraint("best_time_of_day IN ('morning', 'midday', 'afternoon', 'evening', 'anytime')", name='check_task_time'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard', 'very_hard')", name='check_task_difficulty'),
    sa.CheckConstraint("energy_needed IN ('low', 'medium', 'high')", name='check_task_energy'),
    sa.CheckConstraint("focus_needed IN ('low', 'medium', 'high')", name='check_task_focus'),
    sa.CheckConstraint("status IN ('next', 'active', 'waiting', 'someday', 'completed', 'cancelled')", name='check_task_status'),
    sa.CheckConstraint("task_type IN ('creative', 'mechanical', 'admin', 'communication', 'planning')", name='check_task_type'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('wheel_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='check_wheel_score'),
    sa.ForeignKeyConstraint(['category_id'], ['wheel_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_scores_id'), 'wheel_scores', ['id'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('energy_at_start', sa.Integer(), nullable=True),
    sa.Column('focus_at_start', sa.Integer(), nullable=True),
    sa.Column('strategy_used', sa.String(length=100), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('switched_task', sa.Boolean(), nullable=True),
    sa.Column('reason_for_switching', sa.Text(), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.CheckConstraint('effectiveness_rating >= 1 AND effectiveness_rating <= 10', name='check_session_effectiveness'),
    sa.CheckConstraint('energy_at_start >= 1 AND energy_at_start <= 10', name='check_session_energy'),
    sa.CheckConstraint('focus_at_start >= 1 AND focus_at_start <= 10', name='check_session_focus'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_id'), 'work_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_sessions_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_wheel_scores_id'), table_name='wheel_scores')
    op.drop_table('wheel_scores')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_conversation_embeddings_id'), table_name='conversation_embeddings')
    op.drop_table('conversation_embeddings')
    op.drop_index(op.f('ix_wheel_categories_id'), table_name='wheel_categories')
    op.drop_table('wheel_categories')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
