"""add_telegram_fields

Revision ID: dedbd89fad6a
Revises: 42f417f227b3
Create Date: 2026-01-27 13:45:07.277963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dedbd89fad6a'
down_revision: Union[str, Sequence[str], None] = '42f417f227b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversations_session', table_name='conversations')
    op.create_index('idx_conversations_session_id', 'conversations', ['session_id'], unique=False)
    op.alter_column('users', 'adhd_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'adhd_profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_conversations_session_id', table_name='conversations')
    op.create_index('idx_conversations_session', 'conversations', ['session_id'], unique=False)
    # ### end Alembic commands ###
